spring.application.name=airBnbApp

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
soring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.properties.hibernate.format_sql=true